#Actuator运行状态监控配置
management:
  server:
    #actuator端口
    port: 9001
  endpoints:
    web:
      #修改访问路径，默认是/actuator，可以通过此属性修改
      base-path: /
      exposure:
        #开放所有节点，默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      show-details: always

